GET http://localhost:8080/replies/2/votes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJleHAiOjE3MDQyOTAyNjMsInVzZXJJZCI6MX0.7zpe_Sf1xq5lhW6EJW_rnYjUXsJJRr495B1_3TqIVT8
