PUT http://localhost:8080/users/7/password
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGU3QGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2MDI2NTExLCJ1c2VySWQiOjd9.rLpP3UgDofQWphY740E7-sazSRNMiQr8mvLStxy-XgY

{
    "email": "example7@example.com",
    "oldPassword": "password",
    "password" : "password"
}