PUT http://localhost:8080/users/9/password
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGU5QGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2MDkzMDM0LCJ1c2VySWQiOjl9.3-BpCaCdPw6izuTEYDkbcBXrWAf6D5qgzfWsAL2ebMU

{
    "email": "example9@example.com",
    "oldPassword": "password",
    "newPassword" : "password1"
}