DELETE http://localhost:8080/posts/1/votes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NjI1NzQyLCJ1c2VySWQiOjJ9.MMDrPXokdFkN71xVjT3GHppEgW94OM48JjgS69D5oEQ
